[package]
name = "canon-json"
version = "0.2.0"
edition = "2021"
description = "serde_json Formatter to serialize as RFC 8785 canonical JSON"
license = "MIT OR Apache-2.0"
repository = "https://github.com/containers/canon-json-rs"
keywords = ["json"]

[dependencies]
serde        = "1.0.0"
serde_derive = "1.0"
serde_json   = "1.0"
thiserror = "2.0.12"

[dev-dependencies]
proptest = "1.7.0"
similar-asserts = "1.7.0"
cap-std = "3.4.4"
sha2 = "0.10.9"
# For cross-integration testing
olpc-cjson = "0.1"
cjson = "0.1.2"
# For round trip testing
serde_json = { version = "1.0", features = ["float_roundtrip"] }
