[package]
name        = "canon-json"
version     = "0.2.0"
edition     = "2021"
description = "RFC 8785 Canonical JSON serializer"
license     = "MIT"

[dependencies]
serde        = "1.0.0"
serde_derive = "1.0"
serde_json   = "1.0"

[dev-dependencies]
proptest = "1.7.0"
similar-asserts = "1.7.0"

