name: Rust
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Run integration tests
        run: go get github.com/technosophos/canonjson && ./scripts/integration.sh
