name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build && cargo build --target wasm32-unknown-unknown && cargo build --target wasm32-wasi
      - name: Run tests
        run: cargo test
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Run integration tests
        run: |
          export GOPATH=$HOME/go && export GOBIN=$(go env GOPATH)/bin && export PATH=$PATH:$GOPATH && export PATH=$PATH:$GOBIN && mkdir -p $GOBIN
          go get github.com/technosophos/canonjson
          ./scripts/integration.sh
